#!/bin/bash

# Author: Reddysekhar
# Created: 26th Auguest 2023
# Last Modified: 26th Auguest 2023

# Description:
# Creates a backup in the current directory of
# all files in the home directory


name="ReddySekhar"

echo "Hello there, ${name}"
echo "I will now back up your home directory, $HOME"
currentdir=$(pwd)
echo "I will create save the backup file in $currentdir"
tar -cf  "$currentdir/my-backup_$(date +"%Y-%m-%d %H:%M:%S").tar" $HOME 2>/dev/null
echo "Backup Completed Sucessfully."

exit 0
