#!/bin/bash

student="Ramadevi"
echo "Hello ${student}"

---------------------------------------------------------------------------

#!/bin/bash

employee="charan"

echo "Dear ${employee^^},"
echo "The board and i would like to thank you for the excellent work that you have been doing over the last few montns."
echo "keep up the good work, ${employee}"
echo "best wishesh"
echo "CEO | RR Technologies."
